# The numpy.random package

### Programming for Data Analysis 2019

## 1. The overall purpose of the numpy.random package

NumPy (Numerical Python) is a library that is used for scientific computing in Python. It adds support for large 2D and 3D arrays and matrices. 
Numpy.random is a package ..........................

In [1]:
# Importing the packages we will be using
import numpy as np
import matplotlib.pyplot as plt

## 2. The use of the “Simple random data” and “Permutations” functions explained

The simple random data function is used to generate random (I will call them random for now, but I will explain later they are actually pseudorandom) numbers. Below I will shortly explain and show some of the commands that can be used.

In [6]:
# Using the 'rand' command to return an array with random floats (between 0 and 1) in a given shape. 
# In this case an array with 3 columns and 4 rows.
# I used this website for an overview of all Simple random data options the package has to offer: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html
np.random.rand(3, 4)

array([[0.32158328, 0.52910866, 0.48760885, 0.23140069],
       [0.81682472, 0.98462954, 0.45887982, 0.15400232],
       [0.94939551, 0.73024694, 0.02111277, 0.27168999]])

In [12]:
# Using the 'randn' function to return 1 or more arrays with random floats from the "standard normal" distribution,
# of mean 0 and variance 1.
# I used this page to understand this command: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.randn.html#numpy.random.randn
np.random.randn(2, 3, 4)
# 2 arrays which consist of 3 columns and 4 rows.

array([[[ 0.45639052, -0.6398634 ,  0.15301577,  0.03288415],
        [ 0.20534413,  0.30499709, -1.57656675,  1.27806439],
        [ 1.78065453, -0.33596827, -0.32216656, -0.22003104]],

       [[-0.28331172,  0.33461864,  0.07644322,  0.96893456],
        [-1.28129024,  0.87466938, -0.57640212, -0.44150077],
        [ 0.65794421, -2.14265501,  0.18629624, -0.31071687]]])

In [15]:
# The 'randint' function returns integers from low (inclusive) to high (exclusive).
# If there is no high value entered, then results are shown from 0 to 'low'.
# I used this page for more information on this function: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.randint.html#numpy.random.randint
np.random.randint(1, 10, size = 5)
# Generate an array of 5 random integers, between 1 (inclusive) and 10 (exclusive).

array([4, 1, 4, 9, 1])

In [16]:
np.random.random(size = 10)

array([0.36747344, 0.4340795 , 0.88917077, 0.9856484 , 0.46249066,
       0.77480678, 0.73850833, 0.47044273, 0.38942045, 0.90665115])